### PR TITLE
Adding an HTTP error tuple helper class for UIS and PR; upping dependencies

### PR DESCRIPTION
**Pull request by ibaldin**

### CODE REVIEW

**Review by kthare10 — APPROVED** [review]
Looks good

**Review by mjstealey — APPROVED** [review]
+1 

still some outdated packages in the requirements.txt file, but that's a never ending battle

**Comment by ibaldin** [comment]
This is related to https://github.com/fabric-testbed/software-planning/issues/30

**Comment by ibaldin** [comment]
Also related to https://github.com/fabric-testbed/software-planning/issues/25

**Review by kthare10 — APPROVED** [review]

**Pull request merged**
